spring:
  # H2 ?????? ?? ??
  h2:
    console:
      enabled: true  # H2 ?????? ?? ???. ?? ?? ?????? H2 ??????? ??? ? ????.

  # ??? ??(?????? ??) ?? ??
  datasource:
    url: jdbc:h2:mem:testdb # H2 ???? ?????? 'testdb'? ???? ?? JDBC URL ??.
    driver-class-name: org.h2.Driver # H2 ?????? ??? ?? JDBC ???? ???.
    username: sa # ?????? ??? ?? ?? ??? ?? ??.
    password: # ?????? ??? ?? ????. ???? ???????.

  # JPA (Java Persistence API) ?? ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # H2 ??????? ?? ?????? ?? ??.
    hibernate:
      ddl-auto: create-drop # ?????? ?? ? ?????? ???? ???? ?? ? ???? ??.
    properties:
      hibernate:
        format_sql: true # ???? SQL? ?? ?? ???? ??.
        show_sql: true # ??? ???? SQL ?? ??.
    defer-datasource-initialization: true # ??? ?? ???? ?????? ???? ??? ??? ??.

# ?? ?? ??
logging:
  level:
    com.example: DEBUG # 'com.example' ???? ?? ?? ??? DEBUG? ??, ??? ??? ??? ??.
